version: '3.8'

services:
  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/citizen_mdm
    networks:
      - citizen_mdm_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: citizen_mdm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citizen_mdm_network

volumes:
  postgres_data:

networks:
  citizen_mdm_network:
    driver: bridge
